spring:
  application:
    name: GOVIYA-HARVEST-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:9190
        enabled: true
        auto-registration: true
  profiles:
    active: local

server:
  port: 9190
  servlet:
    context-path: /api/goviya-harvest-core

swagger:
  server-url: http://52.118.205.242:9190

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
